### ISSUE TITLE
contentDB download is not compatible with Minetest v5.0+

### ISSUE THREAD

**Issue by b3u** [minetest-mods/skinsdb#25]
Issue  #23 is still relevant if you download skinsDB from contentDB

**Comment by bell07** [comment]
I think we need some "Default" skins to be installed with the mod in contentdb. Currently the mod is useless by default, manual work is needed to install skins.
I asked in forum for proposals https://forum.minetest.net/viewtopic.php?f=11&t=17899&start=50#p345478 but I get no proposals, therefore I did not released the version at contentdb.
Since manually effort needed to install skins, the mod could be installed manually too.

**Comment by b3u** [comment]
True. I have a couple skins for you. I'll add a pull request asap,

**Comment by bell07** [comment]
sirrobzeroone skins was added to "contentdb" branch some times ago. Updated the branch and did new skinsdb release on contentdb
