### ISSUE TITLE
Chat commands to list and set skins

### ISSUE THREAD

**Issue by bell07** [minetest-mods/skinsdb#4]
Some players like to use chat commands instead of Inventory UI. Chat commands should allow to use private skins with unified_inventory and should be useable with all inventories.

Must have
```
/skinsdb list -- List all allowed private and public skins
/skinsdb list private -- List all private (player_playername*) skins
/skinsdb list public-- List all public (character_*) skins
/skinsdb set [skinname] -- Set Skin
```

**Comment by MuhdNurHidayat** [comment]
the command `/skinsdb list private` should just list the user's private skin, not other users' private skin, except for the admin/moderator because they should be able to see all skins...

and one user should not able to set their skin as another user's private skin with chat command, unless they're admin/moderator...

but others might have different view  ¯\_(ツ)_/¯
