### ISSUE TITLE
Depend on player_api, not default

### ISSUE THREAD

**Issue by rubenwardy** [minetest-mods/skinsdb#53]
Is there a reason this mod depends on default over player_api? The player model was moved to player_api

**Comment by bell07** [comment]
You are right, it is just because no one changed it. Now I changed it to player_api in 8048cb08f1baa2da9c6b392a9dfdcf8a8e174f8e.

By the way, it's a catchword to reference to the stripped successor [skinsdb5](https://github.com/bell07/minetest-player_api_modpack/tree/master/skinsdb5) that works only with enhanced player_api provided in the same modpack ;-)
