### ISSUE TITLE
Private skin for players with underscore in the name does not work

### ISSUE THREAD

**Issue by Bastrabun** [minetest-mods/skinsdb#54]
Seems players with underscore in their name cannot find their skins

Repro:

- Have a playername `first_second`
- name the skin `player_first_second_0.png`
- log in as that player and search your private skin
=> Skin is not in the list
- login as admin and search the skin in the list
=> Skin is there, selectable, but says it is called `second 0`

**Comment by SmallJoker** [comment]
Issue in line 27
https://github.com/minetest-mods/skinsdb/blob/8048cb08f1baa2da9c6b392a9dfdcf8a8e174f8e/skinlist.lua#L26-L28

I wonder whether a regex wouldn't fit better there @bell07 ?
```
local prefix, name, ext = fn:match("^(%a+)_(%S+)%.(%a+)")
```
not tested. Might not work due to the greedy `%S+`

**Comment by bell07** [comment]
The current implementation does work as designed. Beside the numbered format `player_[playername]_[number].ext` the skinsdb supports the named format `player_[playername]_[skinname].ext. There is no check for valid player names. player_first_second_0 is player="first" and skinname="second_0". I see no way to get the decision if it is "first_second" / "0" or "first" / "second_0".
But the named format is more important for me because I do not like to create metadata-file for each self-created skin.

**Comment by Bastrabun** [comment]
I only named the personal skin _0 because I had seen that somewhere before. You're right, if someone has a skin with an underscore in its name, we're doomed. Since minetest allows underscore in the name, I believe we need to consider people doing so. We could

- use the current naming scheme unless there is a meta file, telling skins db what exactly is which part
- let [skinname] not have an underscore in them
- find a different truncator that is not allowed by MT names. This might break naming on many servers that go with the current one

**Comment by bell07** [comment]
> use the current naming scheme unless there is a meta file, telling skins db what exactly is which part

This is the way I prefer. In skinsdb5 fork I already changed the meta-file syntax to key = value so there  `player = xyz_xyz` is possible. (Ok, after small fix I do now).  In skinsdb, maybe we can enhance the meta-file syntax the 4th line is the player name?

> let [skinname] not have an underscore in them

The underscore in skin name is replaced to spaces. I use the underscores because some scripties still have issues to manage files with spaces in name.

> find a different truncator that is not allowed by MT names. This might break naming on many servers that go with the current one

Then all server owners need to rename all files :-(
