### ISSUE TITLE
unified inventory tab doesn't work right with skinsdb?

### ISSUE THREAD

**Issue by AmyMoriyama** [minetest-mods/skinsdb#87]
Ok, I'm tired and a little sick so let's see if I can explain this and let's hope I am seeking help with this in the right mod.

So, I just started a new minetest server to play around with. I installed a lot of mods and used the versions in contentdb for the most part. Of these mods, unified inventory and skinsdb are installed.

Minetest 5.8.0-dev-180ec92 (Linux)
Using LuaJIT 2.1.0-beta3
BUILD_TYPE=Release
RUN_IN_PLACE=1
USE_CURL=1
STATIC_SHAREDIR="."

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

This Debian install has been modified using Kicksecure:
https://www.kicksecure.com/wiki/Debian

So, when in the game, I can use the command /skinsdb to change skins but trying to change skins inside unified inventory doesn't work. When I click on a skin, nothing. When I click one of the arrows to change pages, nothing, but I can use the dropdown to change pages.

I can't find any errors anywhere it just doesn't work inside unified inventory. So, is this some kind of bug or conflict or something or did something change somewhere to break things?

I love skinsdb by the way. I really do appreciate this mod.

**Comment by SmallJoker** [comment]
I tried to reproduce your issue using unified_inventory + skinsdb from ContentDB, which both are up-to-date with the source from Git. There is no such behaviour on my side, hence I believe it might be caused by either a mod conflict our outdated mods.
I would recommend you to start a new world only using these two mods and then begin to enable other mods until it stops working.

**Comment by CallMeDax** [comment]
the problem is with unified inventory themes mod. When enabled the skin icon/buttons don't do anything when clicked. They are supposed to change the skin. Using the chat command /skinsdb ui opens a working formspec to change the skin. I don't think it is a fault with this mod, but it would be worth checking.

**Comment by fluxionary** [comment]
https://content.minetest.net/packages/threehymns/unified_inventory_themes/

https://gitlab.com/threehymns1/unified_inventory_themes

**Comment by CallMeDax** [comment]
(I did)
